<?php

/**
 * @file
 * Install, update and uninstall functions for the islandora_metadata_synchronization module.
 */


/**
 * Implements hook_install().
 */
function islandora_metadata_synchronization_install() {
  drupal_mkdir('public://islandora_metadata_synchronization_xsls');
}

/**
 * Implements hook_uninstall().
 */
function islandora_metadata_synchronization_uninstall() {
  $upload_path = 'public://islandora_metadata_synchronization_xsls';
  $removal_files = file_scan_directory($upload_path, '/(.*)/');

  foreach ($removal_files as $file) {
    @file_delete($file);
  }
  drupal_rmdir($upload_path);
}
